version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/timeoff-management
hooks:
  BeforeInstall:
    - location: commands/dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: commands/permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: commands/start_instance.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: commands/stop_instance.sh
      timeout: 300
      runas: root
