version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - echo Nothing to do in the pre-build phase
  
  build:
    commands:
      - echo Building Node.js application
      - npm install
  
  post_build:
    commands:
      - echo Install completed on 'date'

artifacts:
  files:
    - '**/*'
